/*
 * Typing Challenge vocabulary
 *
 * 1 = １年生
 * 2 = ２年生
 * 3 = ３年生
 *
 * Change enabled to false to disable a word without deleting it.
 */

window.VOCAB_DATA = {
  1: [
    { prompt: "（～を）勉強する", answer: "study", enabled: true },
    { prompt: "いつ", answer: "when", enabled: true },
    { prompt: "どこに（で）", answer: "where", enabled: true },
    { prompt: "（～に）勝つ", answer: "win", enabled: true },
    { prompt: "次の、今度の", answer: "next", enabled: true },
    { prompt: "（～を）練習する", answer: "practice", enabled: true },
    { prompt: "熱心に", answer: "hard", enabled: true },
    { prompt: "行く", answer: "go", enabled: true },
    { prompt: "公園", answer: "park", enabled: true },
    { prompt: "駅", answer: "station", enabled: true },
    { prompt: "～の下に（で）", answer: "under", enabled: true },
    { prompt: "7月", answer: "July", enabled: true },
    { prompt: "日曜日", answer: "Sunday", enabled: true },
    { prompt: "月曜日", answer: "Monday", enabled: true },
    { prompt: "火曜日", answer: "Tuesday", enabled: true },
    { prompt: "水曜日", answer: "Wednesday", enabled: true },
    { prompt: "木曜日", answer: "Thursday", enabled: true },
    { prompt: "金曜日", answer: "Friday", enabled: true },
    { prompt: "土曜日", answer: "Saturday", enabled: true },
    { prompt: "なるほど。わかりました。", answer: "I see.", enabled: false },
    { prompt: "がんばって", answer: "Good luck.", enabled: false },
    { prompt: "（～を）料理する", answer: "cook", enabled: true },
    { prompt: "～を飲む", answer: "drink", enabled: true },
    { prompt: "（ある言語を）話す", answer: "speak", enabled: true },
    { prompt: "ふつう、たいてい", answer: "usually", enabled: true },
    { prompt: "今日（は）", answer: "today", enabled: true },
    { prompt: "海", answer: "sea", enabled: true },
    { prompt: "季節", answer: "season", enabled: true },
    { prompt: "おもしろい", answer: "interesting", enabled: true },
    { prompt: "一番好きな、お気に入りの", answer: "favorite", enabled: true },
    { prompt: "キャラクター、登場人物", answer: "character", enabled: true },
    { prompt: "～もまた、そのうえ", answer: "also", enabled: true },
    { prompt: "家族", answer: "family", enabled: true },
    { prompt: "親切な、やさしい", answer: "kind", enabled: true },
    { prompt: "～の近くに", answer: "around / near", enabled: false },
    { prompt: "住む、住んでいる", answer: "live", enabled: true },
    { prompt: "来る", answer: "come", enabled: true },
    { prompt: "歩く、歩いて行く（来る）", answer: "walk", enabled: true },
    { prompt: "すみません。失礼ですが。", answer: "Excuse me.", enabled: true },
    { prompt: "バスで", answer: "by bus", enabled: true },
    { prompt: "放課後", answer: "after school", enabled: true },
    { prompt: "学級、クラス", answer: "class", enabled: true },
    { prompt: "私たちの", answer: "our", enabled: true },
    { prompt: "新しい", answer: "new", enabled: true },
    { prompt: "先生", answer: "teacher", enabled: true },
    { prompt: "チーム", answer: "team", enabled: true },
    { prompt: "かっこいい", answer: "cool", enabled: true },
    { prompt: "いくつかの、いくらかの", answer: "some", enabled: true },
    { prompt: "（両）親", answer: "parent(s)", enabled: false },
    { prompt: "食べ物", answer: "food", enabled: true },
    { prompt: "父親", answer: "father", enabled: true },
    { prompt: "～を作る", answer: "make", enabled: true },
    { prompt: "とても", answer: "very", enabled: true },
    { prompt: "上手に", answer: "well", enabled: true },
    { prompt: "（～を）読む", answer: "read", enabled: true },
    { prompt: "本当に", answer: "really", enabled: true },
    { prompt: "鳥", answer: "bird", enabled: true },
    { prompt: "はい、どうぞ。", answer: "Here you are.", enabled: false },
    { prompt: "ありがとう。", answer: "Thank you.", enabled: false },
    { prompt: "どういたしまして。", answer: "You're welcome.", enabled: false }
  ],

  2: [
    { prompt: "特に", answer: "especially", enabled: true },
    { prompt: "～を注文する", answer: "order", enabled: true },
    { prompt: "いろいろな", answer: "various", enabled: true },
    { prompt: "味、風味", answer: "flavor", enabled: true },
    { prompt: "塩", answer: "salt", enabled: true },
    { prompt: "スピーチ", answer: "speech", enabled: true },
    { prompt: "加える", answer: "add", enabled: true },
    { prompt: "いつか", answer: "sometime", enabled: true },
    { prompt: "（...を）忘れる", answer: "forget", enabled: true },
    { prompt: "濃い、どろっとした", answer: "thick", enabled: true },
    { prompt: "早く", answer: "early", enabled: true },
    { prompt: "食べる", answer: "eat", enabled: true },
    { prompt: "食べた", answer: "ate", enabled: true },
    { prompt: "作る", answer: "make", enabled: true },
    { prompt: "作った", answer: "made", enabled: true },
    { prompt: "反映する", answer: "reflect", enabled: true },
    { prompt: "気候", answer: "climate", enabled: true },
    { prompt: "～したい（のですが）", answer: "would love to ~", enabled: false },
    { prompt: "～に興味がある", answer: "be interested in ~", enabled: false },
    { prompt: "...種類の～", answer: "...kind of ~", enabled: false },
    { prompt: "シェフ", answer: "chef", enabled: true },
    { prompt: "生活/(複数形)", answer: "life / lives", enabled: false },
    { prompt: "外国の", answer: "foreign", enabled: true },
    { prompt: "情報", answer: "information", enabled: true },
    { prompt: "国際的な", answer: "international", enabled: true },
    { prompt: "自分自身の", answer: "own", enabled: true },
    { prompt: "...を選ぶ", answer: "choose", enabled: true },
    { prompt: "...を選んだ", answer: "chose", enabled: true },
    { prompt: "教える", answer: "teach", enabled: true },
    { prompt: "教えた", answer: "taught", enabled: true },
    { prompt: "位置する、ある/(過去)", answer: "lie / lay", enabled: false },
    { prompt: "色彩に富んだ", answer: "colorful", enabled: true },
    { prompt: "かわいい、きれいな", answer: "pretty", enabled: true },
    { prompt: "大切な、重要な", answer: "important", enabled: true },
    { prompt: "...出身である、...から来ている", answer: "come from", enabled: false },
    { prompt: "ここに～があります", answer: "Here is ~.", enabled: false },
    { prompt: "～にちなんで。。。と名づける", answer: "name ...after ~", enabled: false },
    { prompt: "のぼる", answer: "come up", enabled: false },
    { prompt: "...から出てくる", answer: "come out of", enabled: false },
    { prompt: "一つお願いしてもいいですか？", answer: "May I ask you a favor?", enabled: false }
  ],

  3: [
    { prompt: "もう、すでに", answer: "already", enabled: true },
    { prompt: "インタビュー（する）", answer: "interview", enabled: true },
    { prompt: "メッセージ、伝言", answer: "message", enabled: true },
    { prompt: "眠る", answer: "sleep", enabled: true },
    { prompt: "。。。になる／（過去）", answer: "become / became", enabled: false },
    { prompt: "･･･以来、･･･から", answer: "since", enabled: true },
    { prompt: "･･･を導入(紹介)する", answer: "introduce", enabled: true },
    { prompt: "会社/(複数)", answer: "company / companies", enabled: false },
    { prompt: "(･･･に)通じる", answer: "lead", enabled: true },
    { prompt: "もっと少ない", answer: "less", enabled: true },
    { prompt: "否定的な", answer: "negative", enabled: true },
    { prompt: "･･･を含む、含める", answer: "include", enabled: true },
    { prompt: "工場/(複数)", answer: "factory / factories", enabled: false },
    { prompt: "働く。。。", answer: "working", enabled: true },
    { prompt: "働く人", answer: "worker", enabled: true },
    { prompt: "サービス", answer: "service", enabled: true },
    { prompt: "どれくらい（長く、長い）。。。？", answer: "How long...?", enabled: false },
    { prompt: "公平な、公正な", answer: "fair", enabled: true },
    { prompt: "責任のある", answer: "responsible", enabled: true },
    { prompt: "(代金などを)支払う", answer: "pay", enabled: true },
    { prompt: "低い", answer: "low", enabled: true },
    { prompt: "難問、挑戦", answer: "challenge", enabled: true },
    { prompt: "人間の", answer: "human", enabled: true },
    { prompt: "生き残る", answer: "survive", enabled: true },
    { prompt: "困難、めんどう、問題", answer: "trouble", enabled: true },
    { prompt: "気候", answer: "climate", enabled: true },
    { prompt: "情報", answer: "information", enabled: true },
    { prompt: "記事", answer: "article", enabled: true },
    { prompt: "新聞", answer: "newspaper", enabled: true },
    { prompt: "最初の部分、始まり、初め", answer: "beginning", enabled: true },
    { prompt: "世紀", answer: "century", enabled: true },
    { prompt: "･･･にショックを与える", answer: "shock", enabled: true },
    { prompt: "安全に", answer: "safely", enabled: true },
    { prompt: "油、石油", answer: "oil", enabled: true },
    { prompt: "･･･の危険がある", answer: "be in danger of...", enabled: false },
    { prompt: "結果として", answer: "as a result", enabled: false }
  ]

};
